Error from server (AlreadyExists): pods "latest" already exists
NAME     READY   STATUS    RESTARTS   AGE
latest   1/1     Running   0          66s
Forwarding from 127.0.0.1:8000 -> 80
Forwarding from [::1]:8000 -> 80
Handling connection for 8000

//The above is for the terminal window running run_kubernetes.sh


//The below is for when I ran kubectl logs for my pod, which is what a post on knowledge.udacity.com recommended I do
* Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 335-491-932
[2021-07-12 02:12:44,305] INFO in app: JSON payload: 
{'CHAS': {'0': 0}, 'RM': {'0': 6.575}, 'TAX': {'0': 296.0}, 'PTRATIO': {'0': 15.3}, 'B': {'0': 396.9}, 'LSTAT': {'0': 4.98}}
[2021-07-12 02:12:44,317] INFO in app: Inference payload DataFrame: 
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2021-07-12 02:12:44,327] INFO in app: Scaling Payload: 
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2021-07-12 02:12:44,330] INFO in app: Ourput prediction: [20.35373177134412]
127.0.0.1 - - [12/Jul/2021 02:12:44] "POST /predict HTTP/1.1" 200 -
(.devops) voclabs:~/environment/DevOps_Microservices/project-ml-microse
